### ISSUE TITLE
error description

### ISSUE THREAD

**Issue by Vojtak42** [anadius/patcher#1]
Hello, when you are applying more patches at once and on the disc with cache folder is not enough space, the error just says that there was some problem and that i should try to disable antivirus.

**Comment by anadius** [comment]
Can't do much about it. When you apply multiple patches at once - my program is combining the xdelta patches for each file and then applies them all at once. I check if there's enough space but I can't predict how big the combined patch file is.

Here I sum the patches size: https://github.com/anadius/patcher/blob/77405e4f94d63a4f76994c916b4dfe68178431dc/patcher/patcher.py#L1400-L1401

And here I check if there's enough space: https://github.com/anadius/patcher/blob/77405e4f94d63a4f76994c916b4dfe68178431dc/patcher/patcher.py#L1215

See that I even multiply the size times 1.2. IIRC `xdelta3` doesn't return any meaningful error code I can check against when it fails because of a full drive.
