### ISSUE TITLE
Can't apply multiple patches at once

### ISSUE THREAD

**Issue by Vojtak42** [anadius/patcher#2]
Hello,
when i try to apply multiple updates at once, the patch fails. But when i apply one at a time, it completes sucessfully. (SW: Survivor)
I have 2TB space on drive.

**Comment by anadius** [comment]
"the patch fails" tells me nothing.

**Comment by Vojtak42** [comment]
There was no info that would tell me what happened. There was always error with one specific file, I think pakchunk0-WindowsNoEditor.ucas

**Comment by anadius** [comment]
Then you probably ran out of memory, or space, or there's some bug in xdelta3. That's what the Patcher uses under the hood. I only ever tested applying multiple patches at once on files < 4GB. You can try applying 2 patches at once and see if that works.

**Comment by Vojtak42** [comment]
> ran out of memory, or space

I dont think so, i have 2TB space and 32GB memory, I think that it will rather be bug in xdelta3. Its likely due to the file (14GB) size because other smaller files were patched sucessfully.

**Comment by anadius** [comment]
It wasn't due to the file size. A lot of people reported the same problem when using my Updater for TS4. But it was with a 50MB file. Both Patcher and Updater merge patches before applying them - to save time, so you write a x GB file only once.

But some code responsible for merging the patches in `xdelta3` is bugged. Version 1.1.0 detects when patch merging fails and applies the patches one by one. I know it's late and you don't have the files anymore to confirm it but it *should* be resolved now.
